//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;

    public partial class Login
    {
        // public HttpResponseMessage responseMsg { get; set; }

        public int userID { get; set; }
        public string UserName { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
        public string Salt { get; set; }
    }
}
